import { Injectable } from '@angular/core';
import { Observable, Subject } from 'rxjs';
import { RowService } from './row.service';
import { GeneralService } from './general.service';
import { StyleService } from './style.service';
import { SectionService } from './section.service';
import { CdkDropList } from '@angular/cdk/drag-drop';

@Injectable({
  providedIn: 'root'
})
export class ElementService {

  public elementConnect: CdkDropList[] = [];

  distroyDialogue = new Subject<any>();
  elementObj: any = {id: '', name: '',  type: 'element', content: {}, setting: false, 
                    item_alignment: {desktop: '', tablet_h: 'auto', tablet_v: 'auto', mobile: 'auto'}, 
                    redirection: {link: '', target: '_self' },
                    style: {desktop: '', tablet_h: '', tablet_v: '', mobile: '', hover: ''}, 
                    hide: {desktop: false, tablet_h: false, tablet_v: false, mobile: false}};
  element_index = 0;
  selectedElements: any = [];
  elementList: any = {
    // heading
    heading: {
      content: {
        name: 'heading',
        html: `<h2>Heading goes here</h2>`,
        size: 38,
        editor: false,
      }, iconCls: 'fas fa-heading'},
    // heading
    // text
    text: {
      content: {
        name: 'text',
        html: `<p>Kea Builder is named after the parrot Kea. Kea is one of the smartest birds on earth. The Kea is a species of largest parrot in the family Nestoridae found in the forested and alpine regions of the South Island of New Zealand.</p>`,
        size: 16,
        editor: false,
      }, iconCls: 'fas fa-font'},
    // text
    // image
    image: { content: { name: 'image', src: '' }, iconCls: 'far fa-image'},
    // image
    // video
    video: {
      content: {
        name: 'video',
        type: 'video',
        iframe: '<iframe width="560" height="315" src="http://localhost:4200/assets/videos/movie.mp4" title="Video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe>',
        src: 'http://localhost:4200/assets/videos/movie.mp4',
        autoplay: false,
        muted: false,
        loop: false,
        controls: true
      }, iconCls: 'fas fa-video'},
    // video
    // button
    button: { 
      content: { 
        name: 'button', size: 14, btntype: 'regular', 
        text: 'Read More', subtext: '', subfont_size: '80%', 
        link: '#no-link', target: '_self' 
      }, iconCls: 'fas fa-toggle-off'},
    // button
    // menu
    menu: { content: { name: 'menu', size: 16, items: []}, iconCls: 'fas fa-bars'},
    // menu
    // divider
    divider: { content: { name: 'divider' }, iconCls: 'fas fa-minus'},
    // divider
    // form
    form: { content: { name: 'iframe', type: 'form', src: '', height: '' }, iconCls: 'fab fa-wpforms'},
    // form
    // code block
    code: { content: { name: 'code', html: ``}, iconCls: 'fas fa-code' },
    // code block
    // icon
    icon: { content: { name: 'icon', html: `<i class="fa-solid fa-icons"></i>`, size: 18,}, iconCls: 'fa-solid fa-icons' },
    // icon
    // checkout form
    // append
    // checkout form
  };
  preMenuItems: any = ['Home', 'About', 'Blog', 'Contact'];
  defaultIcons: any = [
    {name: 'fa-solid fa-person-digging', type: 'solid'},
    {name: 'fa-solid fa-people-group', type: 'solid'},
    {name: 'fa-solid fa-id-card', type: 'solid'},
    {name: 'fa-solid fa-taxi', type: 'solid'},
    {name: 'fa-solid fa-house', type: 'solid'},
    {name: 'fa-solid fa-pause', type: 'solid'},
    {name: 'fa-solid fa-house-signal', type: 'solid'},
    {name: 'fa-solid fa-house-lock', type: 'solid'},
    {name: 'fa-solid fa-phone', type: 'solid'},
    {name: 'fa-solid fa-phone-volume', type: 'solid'},
    {name: 'fa-solid fa-mobile', type: 'solid'},
    {name: 'fa-solid fa-signal', type: 'solid'},
    {name: 'fa-solid fa-headphones', type: 'solid'},
    {name: 'fa-solid fa-microphone', type: 'solid'},
    {name: 'fa-solid fa-microphone-slash', type: 'solid'},
    {name: 'fa-solid fa-battery-full', type: 'solid'},
    {name: 'fa-solid fa-computer', type: 'solid'},
    {name: 'fa-solid fa-power-off', type: 'solid'},
    {name: 'fa-solid fa-tower-broadcast', type: 'solid'},
    {name: 'fa-solid fa-tower-cell', type: 'solid'},
    {name: 'fa-solid fa-laptop', type: 'solid'},
    {name: 'fa-solid fa-laptop-code', type: 'solid'},
    {name: 'fa-solid fa-message', type: 'solid'},
    {name: 'fa-solid fa-envelope', type: 'solid'},
    {name: 'fa-solid fa-comment', type: 'solid'},
    {name: 'fa-solid fa-inbox', type: 'solid'},
    {name: 'fa-solid fa-comments', type: 'solid'},
    {name: 'fa-solid fa-reply', type: 'solid'},
    {name: 'fa-solid fa-spa', type: 'solid'},
    {name: 'fa-solid fa-hashtag', type: 'solid'},
    {name: 'fa-solid fa-share', type: 'solid'},
    {name: 'fa-solid fa-arrow-right', type: 'solid'},
    {name: 'fa-solid fa-arrow-up', type: 'solid'},
    {name: 'fa-solid fa-arrow-down', type: 'solid'},
    {name: 'fa-solid fa-arrow-left', type: 'solid'},
    {name: 'fa-solid fa-arrow-up-from-bracket', type: 'solid'},
    {name: 'fa-solid fa-arrow-rotate-right', type: 'solid'},
    {name: 'fa-solid fa-arrow-pointer', type: 'solid'},
    {name: 'fa-solid fa-location-arrow', type: 'solid'},
    {name: 'fa-solid fa-location-crosshairs', type: 'solid'},
    {name: 'fa-solid fa-location-dot', type: 'solid'},
    {name: 'fa-solid fa-location-pin', type: 'solid'},
    {name: 'fa-solid fa-location-pin-lock', type: 'solid'},
    {name: 'fa-solid fa-plane', type: 'solid'},
    {name: 'fa-solid fa-globe', type: 'solid'},
    {name: 'fa-solid fa-compass', type: 'solid'},
    {name: 'fa-solid fa-map-pin', type: 'solid'},
    {name: 'fa-solid fa-map', type: 'solid'},
    {name: 'fa-solid fa-car', type: 'solid'},
    {name: 'fa-solid fa-bus', type: 'solid'},
    {name: 'fa-solid fa-heart', type: 'solid'},
    {name: 'fa-solid fa-diamond', type: 'solid'},
    {name: 'fa-solid fa-user', type: 'solid'},
    {name: 'fa-solid fa-users', type: 'solid'},
    {name: 'fa-solid fa-user-secret', type: 'solid'},
    {name: 'fa-solid fa-user-minus', type: 'solid'},
    {name: 'fa-solid fa-user-nurse', type: 'solid'},
    {name: 'fa-solid fa-user-plus', type: 'solid'},
    {name: 'fa-solid fa-user-tie', type: 'solid'},
    {name: 'fa-solid fa-users-viewfinder', type: 'solid'},
    {name: 'fa-solid fa-users-slash', type: 'solid'},
    {name: 'fa-solid fa-users-rectangle', type: 'solid'},
    {name: 'fa-solid fa-users-rays', type: 'solid'},
    {name: 'fa-solid fa-users-line', type: 'solid'},
    {name: 'fa-solid fa-users-gear', type: 'solid'},
    {name: 'fa-solid fa-users-between-lines', type: 'solid'},
    {name: 'fa-solid fa-user-xmark', type: 'solid'},
    {name: 'fa-solid fa-user-tag', type: 'solid'},
    {name: 'fa-solid fa-user-slash', type: 'solid'},
    {name: 'fa-solid fa-user-shield', type: 'solid'},
    {name: 'fa-solid fa-user-pen', type: 'solid'},
    {name: 'fa-solid fa-user-ninja', type: 'solid'},
    {name: 'fa-solid fa-user-group', type: 'solid'},
    {name: 'fa-solid fa-user-graduate', type: 'solid'},
    {name: 'fa-solid fa-user-gear', type: 'solid'},
    {name: 'fa-solid fa-user-doctor', type: 'solid'},
    {name: 'fa-solid fa-user-clock', type: 'solid'},
    {name: 'fa-solid fa-user-check', type: 'solid'},
    {name: 'fa-solid fa-user-astronaut', type: 'solid'},
    {name: 'fa-solid fa-circle-user', type: 'solid'},
    {name: 'fa-solid fa-house-user', type: 'solid'},
    {name: 'fa-solid fa-hospital-user', type: 'solid'},
    {name: 'fa-solid fa-clipboard-user', type: 'solid'},
    {name: 'fa-solid fa-chalkboard-user', type: 'solid'},
    {name: 'fa-solid fa-building-user', type: 'solid'},
    {name: 'fa-solid fa-house-chimney-user', type: 'solid'},
    {name: 'fa-solid fa-baby', type: 'solid'},
    {name: 'fa-solid fa-people-arrows', type: 'solid'},
    {name: 'fa-solid fa-wheelchair', type: 'solid'},
    {name: 'fa-solid fa-universal-access', type: 'solid'},
    {name: 'fa-solid fa-people-carry-box', type: 'solid'},
    {name: 'fa-solid fa-poo', type: 'solid'},
    {name: 'fa-solid fa-face-smile', type: 'solid'},
    {name: 'fa-solid fa-person', type: 'solid'},
    {name: 'fa-solid fa-person-dress', type: 'solid'},
    {name: 'fa-solid fa-address-book', type: 'solid'},
    {name: 'fa-solid fa-street-view', type: 'solid'},
    {name: 'fa-solid fa-address-card', type: 'solid'},
    {name: 'fa-solid fa-restroom', type: 'solid'},
    {name: 'fa-solid fa-child', type: 'solid'},
    {name: 'fa-solid fa-skull', type: 'solid'},
    {name: 'fa-solid fa-person-walking-with-cane', type: 'solid'},
    {name: 'fa-solid fa-person-walking-luggage', type: 'solid'},
    {name: 'fa-solid fa-person-walking', type: 'solid'},
    {name: 'fa-solid fa-person-shelter', type: 'solid'},
    {name: 'fa-solid fa-person-running', type: 'solid'},
    {name: 'fa-solid fa-person-pregnant', type: 'solid'},
    {name: 'fa-solid fa-person-praying', type: 'solid'},
    {name: 'fa-solid fa-person-hiking', type: 'solid'},
    {name: 'fa-solid fa-person-drowning', type: 'solid'},
    {name: 'fa-solid fa-people-roof', type: 'solid'},
    {name: 'fa-solid fa-person-biking', type: 'solid'},
    {name: 'fa-solid fa-head-side-virus', type: 'solid'},
    {name: 'fa-solid fa-children', type: 'solid'},
    {name: 'fa-solid fa-child-reaching', type: 'solid'},
    {name: 'fa-solid fa-house-flag', type: 'solid'},
    {name: 'fa-solid fa-industry', type: 'solid'},
    {name: 'fa-solid fa-viruses', type: 'solid'},
    {name: 'fa-solid fa-computer-mouse', type: 'solid'},
    {name: 'fa-solid fa-mug-saucer', type: 'solid'},
    {name: 'fa-solid fa-warehouse', type: 'solid'},
    {name: 'fa-solid fa-server', type: 'solid'},
    {name: 'fa-solid fa-peace', type: 'solid'},
    {name: 'fa-solid fa-staff-snake', type: 'solid'},
    {name: 'fa-solid fa-dragon', type: 'solid'},
    {name: 'fa-solid fa-tower-observation', type: 'solid'},
    {name: 'fa-solid fa-bell-concierge', type: 'solid'},
    {name: 'fa-solid fa-image', type: 'solid'},
    {name: 'fa-solid fa-bars', type: 'solid'},
    {name: 'fa-solid fa-star', type: 'solid'},
    {name: 'fa-solid fa-music', type: 'solid'},
    {name: 'fa-solid fa-cloud', type: 'solid'},
    {name: 'fa-solid fa-pen-nib', type: 'solid'},
    {name: 'fa-solid fa-paperclip', type: 'solid'},
    {name: 'fa-solid fa-file', type: 'solid'},
    {name: 'fa-solid fa-bell', type: 'solid'},
    {name: 'fa-solid fa-cart-shopping', type: 'solid'},
    {name: 'fa-solid fa-clipboard', type: 'solid'},
    {name: 'fa-solid fa-filter', type: 'solid'},
    {name: 'fa-solid fa-alarm-clock', type: 'solid'},
    {name: 'fa-solid fa-bolt', type: 'solid'},
    {name: 'fa-solid fa-ghost', type: 'solid'},
    {name: 'fa-solid fa-rocket-launch', type: 'solid'},
    {name: 'fa-solid fa-pen', type: 'solid'},
    {name: 'fa-solid fa-umbrella', type: 'solid'},
    {name: 'fa-solid fa-gift', type: 'solid'},
    {name: 'fa-solid fa-film', type: 'solid'},
    {name: 'fa-regular fa-film', type: 'solid'},
    {name: 'fa-solid fa-gear', type: 'solid'},
    {name: 'fa-solid fa-trash', type: 'solid'},
    {name: 'fa-solid fa-sparkles', type: 'solid'},
    {name: 'fa-solid fa-lock', type: 'solid'},
    {name: 'fa-solid fa-volume', type: 'solid'},
    {name: 'fa-solid fa-barcode', type: 'solid'},
    {name: 'fa-solid fa-tag', type: 'solid'},
    {name: 'fa-solid fa-book', type: 'solid'},
    {name: 'fa-solid fa-bookmark', type: 'solid'},
    {name: 'fa-solid fa-print', type: 'solid'},
    {name: 'fa-solid fa-fire', type: 'solid'},
    {name: 'fa-solid fa-camera', type: 'solid'},
    {name: 'fa-solid fa-video', type: 'solid'},
    {name: 'fa-solid fa-droplet', type: 'solid'},
    {name: 'fa-solid fa-eye', type: 'solid'},
    {name: 'fa-solid fa-magnet', type: 'solid'},
    {name: 'fa-solid fa-hand', type: 'solid'},
    {name: 'fa-solid fa-folder', type: 'solid'},
    {name: 'fa-solid fa-folder-open', type: 'solid'},
    {name: 'fa-solid fa-thumbs-up', type: 'solid'},
    {name: 'fa-solid fa-thumbs-down', type: 'solid'},
    {name: 'fa-solid fa-key', type: 'solid'},
    {name: 'fa-solid fa-thumbtack', type: 'solid'},
    {name: 'fa-solid fa-gears', type: 'solid'},
    {name: 'fa-solid fa-paper-plane', type: 'solid'},
    {name: 'fa-solid fa-truck', type: 'solid'},
    {name: 'fa-solid fa-city', type: 'solid'},
    {name: 'fa-solid fa-tree', type: 'solid'},
    {name: 'fa-solid fa-wifi', type: 'solid'},
    {name: 'fa-solid fa-window', type: 'solid'},
    {name: 'fa-solid fa-burger-soda', type: 'solid'},
    {name: 'fa-solid fa-paint-roller', type: 'solid'},
    {name: 'fa-solid fa-bicycle', type: 'solid'},
    {name: 'fa-solid fa-sliders', type: 'solid'},
    {name: 'fa-solid fa-brush', type: 'solid'},
    {name: 'fa-solid fa-flask', type: 'solid'},
    {name: 'fa-solid fa-briefcase', type: 'solid'},
    {name: 'fa-solid fa-balloons', type: 'solid'},
    {name: 'fa-solid fa-bath', type: 'solid'},
    {name: 'fa-solid fa-handshake', type: 'solid'},
    {name: 'fa-solid fa-snowflake', type: 'solid'},
    {name: 'fa-solid fa-palette', type: 'solid'},
    {name: 'fa-solid fa-layer-group', type: 'solid'},
    {name: 'fa-solid fa-brackets-curly', type: 'solid'},
    {name: 'fa-solid fa-gamepad', type: 'solid'},
    {name: 'fa-solid fa-feather', type: 'solid'},
    {name: 'fa-solid fa-sun', type: 'solid'},
    {name: 'fa-solid fa-computer-classic', type: 'solid'},
    {name: 'fa-solid fa-link', type: 'solid'},
    {name: 'fa-solid fa-play-pause', type: 'solid'},
    {name: 'fa-solid fa-bug', type: 'solid'},
    {name: 'fa-solid fa-shop', type: 'solid'},
    {name: 'fa-solid fa-joystick', type: 'solid'},
    {name: 'fa-solid fa-planet-ringed', type: 'solid'},
    {name: 'fa-solid fa-landmark', type: 'solid'},
    {name: 'fa-solid fa-chart-simple', type: 'solid'},
    {name: 'fa-solid fa-shirt', type: 'solid'},
    {name: 'fa-solid fa-files', type: 'solid'},
    {name: 'fa-solid fa-dolphin', type: 'solid'},
    {name: 'fa-solid fa-anchor', type: 'solid'},
    {name: 'fa-solid fa-quote-left', type: 'solid'},
    {name: 'fa-solid fa-atom-simple', type: 'solid'},
    {name: 'fa-solid fa-bag-shopping', type: 'solid'},
    {name: 'fa-solid fa-bed-front', type: 'solid'},
    {name: 'fa-solid fa-signal-bars', type: 'solid'},
    {name: 'fa-solid fa-code-compare', type: 'solid'},
    {name: 'fa-solid fa-stethoscope', type: 'solid'},
    {name: 'fa-solid fa-car-side', type: 'solid'},
    {name: 'fa-solid fa-ufo', type: 'solid'},
    {name: 'fa-solid fa-aperture', type: 'solid'},
    {name: 'fa-solid fa-bird', type: 'solid'},
    {name: 'fa-solid fa-strawberry', type: 'solid'},
    {name: 'fa-solid fa-crab', type: 'solid'},
    {name: 'fa-solid fa-cable-car', type: 'solid'},
    {name: 'fa-solid fa-moped', type: 'solid'},
    {name: 'fa-solid fa-info', type: 'solid'},
    {name: 'fa-solid fa-play', type: 'solid'},
    {name: 'fa-solid fa-passport', type: 'solid'},
    {name: 'fa-solid fa-question', type: 'solid'},
    {name: 'fa-solid fa-pencil', type: 'solid'},
    {name: 'fa-solid fa-head-side', type: 'solid'},
    {name: 'fa-solid fa-upload', type: 'solid'},
    {name: 'fa-solid fa-computer-speaker', type: 'solid'},
    {name: 'fa-solid fa-database', type: 'solid'},
    {name: 'fa-solid fa-newspaper', type: 'solid'},
    {name: 'fa-solid fa-building', type: 'solid'},
    {name: 'fa-solid fa-globe-stand', type: 'solid'},
    {name: 'fa-solid fa-store', type: 'solid'},
    {name: 'fa-solid fa-file-excel', type: 'solid'},
    {name: 'fa-solid fa-browser', type: 'solid'},
    {name: 'fa-solid fa-shield', type: 'solid'},
    {name: 'fa-solid fa-expand', type: 'solid'},
    {name: 'fa-solid fa-water', type: 'solid'},
    {name: 'fa-solid fa-coin', type: 'solid'},
    {name: 'fa-solid fa-rocket', type: 'solid'},
    {name: 'fa-solid fa-spinner', type: 'solid'},
    {name: 'fa-solid fa-signature', type: 'solid'},
    {name: 'fa-solid fa-icons', type: 'solid'},
    {name: 'fa-solid fa-desktop', type: 'solid'},
    {name: 'fa-solid fa-watch', type: 'solid'},
    {name: 'fa-solid fa-vials', type: 'solid'},
    {name: 'fa-solid fa-language', type: 'solid'},
    {name: 'fa-solid fa-brain', type: 'solid'},
    {name: 'fa-solid fa-hotel', type: 'solid'},
    {name: 'fa-solid fa-marker', type: 'solid'},
    {name: 'fa-solid fa-shower', type: 'solid'},
    {name: 'fa-solid fa-glass', type: 'solid'},
    {name: 'fa-solid fa-mailbox', type: 'solid'},
    {name: 'fa-solid fa-badge', type: 'solid'},
    {name: 'fa-solid fa-wallet', type: 'solid'},
    {name: 'fa-solid fa-award', type: 'solid'},
    {name: 'fa-solid fa-toggle-on', type: 'solid'},
    {name: 'fa-solid fa-ship', type: 'solid'},
    {name: 'fa-solid fa-hands', type: 'solid'},
    {name: 'fa-solid fa-radar', type: 'solid'},
    {name: 'fa-solid fa-motorcycle', type: 'solid'},
    {name: 'fa-solid fa-text-size', type: 'solid'},
    {name: 'fa-solid fa-train', type: 'solid'},
    {name: 'fa-solid fa-books', type: 'solid'},
    {name: 'fa-solid fa-wrench', type: 'solid'},
    {name: 'fa-solid fa-microchip', type: 'solid'},
    {name: 'fa-solid fa-trophy', type: 'solid'},
    {name: 'fa-solid fa-hammer', type: 'solid'},
    {name: 'fa-solid fa-file-pdf', type: 'solid'},
    {name: 'fa-solid fa-solar-system', type: 'solid'},
    {name: 'fa-solid fa-scanner-touchscreen', type: 'solid'},
    {name: 'fa-solid fa-meat', type: 'solid'},
    {name: 'fa-solid fa-radio', type: 'solid'},
    {name: 'fa-solid fa-album', type: 'solid'},
    {name: 'fa-solid fa-chair', type: 'solid'},
    {name: 'fa-solid fa-route', type: 'solid'},
    {name: 'fa-solid fa-plug', type: 'solid'},
    {name: 'fa-solid fa-calculator', type: 'solid'},
    {name: 'fa-solid fa-certificate', type: 'solid'},
    {name: 'fa-solid fa-fingerprint', type: 'solid'},
    {name: 'fa-solid fa-road', type: 'solid'},
    {name: 'fa-solid fa-crosshairs', type: 'solid'},
    {name: 'fa-solid fa-heading', type: 'solid'},
    {name: 'fa-solid fa-church', type: 'solid'},
    {name: 'fa-solid fa-joint', type: 'solid'},
    {name: 'fa-solid fa-recycle', type: 'solid'},
    {name: 'fa-solid fa-lightbulb', type: 'solid'},
    {name: 'fa-solid fa-staff', type: 'solid'},
    {name: 'fa-solid fa-stamp', type: 'solid'},
    {name: 'fa-solid fa-kidneys', type: 'solid'},
    {name: 'fa-solid fa-microwave', type: 'solid'},
    {name: 'fa-solid fa-wreath', type: 'solid'},
    {name: 'fa-solid fa-window-frame', type: 'solid'},
    {name: 'fa-solid fa-wifi-slash', type: 'solid'},
    {name: 'fa-solid fa-waveform', type: 'solid'},
    {name: 'fa-solid fa-wand', type: 'solid'},
    {name: 'fa-solid fa-tv', type: 'solid'},
    {name: 'fa-solid fa-trumpet', type: 'solid'},
    {name: 'fa-solid fa-truck-moving', type: 'solid'},
    {name: 'fa-solid fa-truck-flatbed', type: 'solid'},
    {name: 'fa-solid fa-trash-can', type: 'solid'},
    {name: 'fa-solid fa-tooth', type: 'solid'},
    {name: 'fa-solid fa-timeline', type: 'solid'},
    {name: 'fa-solid fa-tent', type: 'solid'},
    {name: 'fa-solid fa-teeth', type: 'solid'},
    {name: 'fa-solid fa-tarp', type: 'solid'},
    {name: 'fa-solid fa-suitcase', type: 'solid'},
    {name: 'fa-solid fa-stopwatch', type: 'solid'},
    {name: 'fa-solid fa-stapler', type: 'solid'},
    {name: 'fa-solid fa-stairs', type: 'solid'},
    {name: 'fa-solid fa-spoon', type: 'solid'},
    {name: 'fa-regular fa-spoon', type: 'solid'},
    {name: 'fa-solid fa-socks', type: 'solid'},
    {name: 'fa-solid fa-snowman', type: 'solid'},
    {name: 'fa-solid fa-snooze', type: 'solid'},
    {name: 'fa-solid fa-snake', type: 'solid'},
    {name: 'fa-solid fa-smoking', type: 'solid'},
    {name: 'fa-solid fa-skull-crossbones', type: 'solid'},
    {name: 'fa-solid fa-siren-on', type: 'solid'},
    {name: 'fa-solid fa-sidebar', type: 'solid'},
    {name: 'fa-solid fa-shovel', type: 'solid'},
    {name: 'fa-solid fa-shoe-prints', type: 'solid'},
    {name: 'fa-solid fa-shield-quartered', type: 'solid'},
    {name: 'fa-solid fa-share-nodes', type: 'solid'},
    {name: 'fa-solid fa-sheet-plastic', type: 'solid'},
    {name: 'fa-solid fa-share-all', type: 'solid'},
    {name: 'fa-solid fa-shapes', type: 'solid'},
    {name: 'fa-solid fa-sensor', type: 'solid'},
    {name: 'fa-solid fa-scarf', type: 'solid'},
    {name: 'fa-solid fa-screen-users', type: 'solid'},
    {name: 'fa-solid fa-scissors', type: 'solid'},
    {name: 'fa-solid fa-scalpel', type: 'solid'},
    {name: 'fa-solid fa-scanner-image', type: 'solid'},
    {name: 'fa-solid fa-saxophone', type: 'solid'},
    {name: 'fa-solid fa-sailboat', type: 'solid'},
    {name: 'fa-solid fa-sack', type: 'solid'},
    {name: 'fa-solid fa-rug', type: 'solid'},
    {name: 'fa-solid fa-rss', type: 'solid'},
    {name: 'fa-solid fa-router', type: 'solid'},
    {name: 'fa-solid fa-road-barrier', type: 'solid'},
    {name: 'fa-solid fa-ribbon', type: 'solid'},
    {name: 'fa-solid fa-reel', type: 'solid'},
    {name: 'fa-solid fa-ram', type: 'solid'},
    {name: 'fa-solid fa-rainbow', type: 'solid'},
    {name: 'fa-solid fa-rabbit', type: 'solid'},
    {name: 'fa-solid fa-quotes', type: 'solid'},
    {name: 'fa-solid fa-q', type: 'solid'},
    {name: 'fa-solid fa-puzzle', type: 'solid'},
    {name: 'fa-solid fa-pump', type: 'solid'},
    {name: 'fa-solid fa-popcorn', type: 'solid'},
    {name: 'fa-solid fa-prescription', type: 'solid'},
    {name: 'fa-solid fa-podcast', type: 'solid'},
    {name: 'fa-solid fa-pizza-slice', type: 'solid'},
    {name: 'fa-solid fa-pipe', type: 'solid'},
    {name: 'fa-solid fa-person-swimming', type: 'solid'},
    {name: 'fa-solid fa-paw', type: 'solid'},
    {name: 'fa-solid fa-paragraph', type: 'solid'},
    {name: 'fa-solid fa-paper-plane-top', type: 'solid'},
    {name: 'fa-solid fa-panorama', type: 'solid'},
    {name: 'fa-solid fa-pancakes', type: 'solid'},
    {name: 'fa-solid fa-pallet', type: 'solid'},
    {name: 'fa-solid fa-pager', type: 'solid'},
    {name: 'fa-solid fa-page', type: 'solid'},
    {name: 'fa-solid fa-oven', type: 'solid'},
    {name: 'fa-solid fa-ornament', type: 'solid'},
    {name: 'fa-solid fa-onion', type: 'solid'},
    {name: 'fa-solid fa-oil-can', type: 'solid'},
    {name: 'fa-solid fa-oil-can-drip', type: 'solid'},
    {name: 'fa-solid fa-olive', type: 'solid'},
    {name: 'fa-solid fa-nose', type: 'solid'},
    {name: 'fa-solid fa-music-note', type: 'solid'},
    {name: 'fa-solid fa-mountain', type: 'solid'},
    {name: 'fa-solid fa-merge', type: 'solid'},
    {name: 'fa-solid fa-mercury', type: 'solid'},
    {name: 'fa-solid fa-memory', type: 'solid'},
    {name: 'fa-solid fa-mask-face', type: 'solid'},
    {name: 'fa-solid fa-mango', type: 'solid'},
    {name: 'fa-solid fa-mandolin', type: 'solid'},
    {name: 'fa-solid fa-lips', type: 'solid'},
    {name: 'fa-solid fa-memo', type: 'solid'},
    {name: 'fa-solid fa-knife', type: 'solid'},
    {name: 'fa-solid fa-kiwi-fruit', type: 'solid'},
    {name: 'fa-solid fa-jug', type: 'solid'},
    {name: 'fa-solid fa-jug-bottle', type: 'solid'},
    {name: 'fa-solid fa-jar', type: 'solid'},
    {name: 'fa-solid fa-inboxes', type: 'solid'},
    {name: 'fa-solid fa-inbox-out', type: 'solid'},
    {name: 'fa-solid fa-inbox-in', type: 'solid'},
    {name: 'fa-solid fa-inbox-full', type: 'solid'},
    {name: 'fa-solid fa-helicopter-symbol', type: 'solid'},
    {name: 'fa-solid fa-helicopter', type: 'solid'},
    {name: 'fa-solid fa-gun', type: 'solid'},
    {name: 'fa-solid fa-graduation-cap', type: 'solid'},
    {name: 'fa-solid fa-gif', type: 'solid'},
    {name: 'fa-solid fa-football-helmet', type: 'solid'},
    {name: 'fa-solid fa-flashlight', type: 'solid'},
    {name: 'fa-solid fa-filters', type: 'solid'},
    {name: 'fa-solid fa-fill', type: 'solid'},
    {name: 'fa-solid fa-file-prescription', type: 'solid'},
    {name: 'fa-solid fa-file-powerpoint', type: 'solid'},
    {name: 'fa-solid fa-file-pen', type: 'solid'},
    {name: 'fa-solid fa-file-music', type: 'solid'},
    {name: 'fa-solid fa-ferris-wheel', type: 'solid'},
    {name: 'fa-solid fa-escalator', type: 'solid'},
    {name: 'fa-solid fa-engine', type: 'solid'},
    {name: 'fa-solid fa-egg', type: 'solid'},
    {name: 'fa-solid fa-cowbell', type: 'solid'},
    {name: 'fa-solid fa-comment-sms', type: 'solid'},
    {name: 'fa-solid fa-clapperboard', type: 'solid'},
    {name: 'fa-solid fa-check-double', type: 'solid'},
    {name: 'fa-solid fa-castle', type: 'solid'},
    {name: 'fa-solid fa-cards-blank', type: 'solid'},
    {name: 'fa-solid fa-cactus', type: 'solid'},
    {name: 'fa-solid fa-butter', type: 'solid'},
    {name: 'fa-solid fa-burger', type: 'solid'},
    {name: 'fa-solid fa-bone', type: 'solid'},
    {name: 'fa-solid fa-bolt-lightning', type: 'solid'},
    {name: 'fa-solid fa-bluetooth', type: 'solid'},
    {name: 'fa-solid fa-block-brick', type: 'solid'},
    {name: 'fa-solid fa-apartment', type: 'solid'},
    {name: 'fa-solid fa-apostrophe', type: 'solid'},
    {name: 'fa-regular fa-person-digging', type: 'regular'},
    {name: 'fa-regular fa-people-group', type: 'regular'},
    {name: 'fa-regular fa-id-card', type: 'regular'},
    {name: 'fa-regular fa-taxi', type: 'regular'},
    {name: 'fa-regular fa-house', type: 'regular'},
    {name: 'fa-regular fa-pause', type: 'regular'},
    {name: 'fa-regular fa-house-signal', type: 'regular'},
    {name: 'fa-regular fa-house-lock', type: 'regular'},
    {name: 'fa-regular fa-phone', type: 'regular'},
    {name: 'fa-regular fa-phone-volume', type: 'regular'},
    {name: 'fa-regular fa-mobile', type: 'regular'},
    {name: 'fa-regular fa-signal', type: 'regular'},
    {name: 'fa-regular fa-headphones', type: 'regular'},
    {name: 'fa-regular fa-microphone', type: 'regular'},
    {name: 'fa-regular fa-microphone-slash', type: 'regular'},
    {name: 'fa-regular fa-battery-full', type: 'regular'},
    {name: 'fa-regular fa-computer', type: 'regular'},
    {name: 'fa-regular fa-power-off', type: 'regular'},
    {name: 'fa-regular fa-tower-broadcast', type: 'regular'},
    {name: 'fa-regular fa-tower-cell', type: 'regular'},
    {name: 'fa-regular fa-laptop', type: 'regular'},
    {name: 'fa-regular fa-laptop-code', type: 'regular'},
    {name: 'fa-regular fa-message', type: 'regular'},
    {name: 'fa-regular fa-envelope', type: 'regular'},
    {name: 'fa-regular fa-comment', type: 'regular'},
    {name: 'fa-regular fa-inbox', type: 'regular'},
    {name: 'fa-solid fa-comments', type: 'regular'},
    {name: 'fa-regular fa-reply', type: 'regular'},
    {name: 'fa-light fa-spa', type: 'regular'},
    {name: 'fa-regular fa-hashtag', type: 'regular'},
    {name: 'fa-regular fa-share', type: 'regular'},
    {name: 'fa-regular fa-arrow-right', type: 'regular'},
    {name: 'fa-regular fa-arrow-up', type: 'regular'},
    {name: 'fa-regular fa-arrow-down', type: 'regular'},
    {name: 'fa-regular fa-arrow-left', type: 'regular'},
    {name: 'fa-regular fa-arrow-up-from-bracket', type: 'regular'},
    {name: 'fa-regular fa-arrow-rotate-right', type: 'regular'},
    {name: 'fa-regular fa-arrow-pointer', type: 'regular'},
    {name: 'fa-regular fa-location-arrow', type: 'regular'},
    {name: 'fa-regular fa-location-crosshairs', type: 'regular'},
    {name: 'fa-regular fa-location-dot', type: 'regular'},
    {name: 'fa-regular fa-location-pin', type: 'regular'},
    {name: 'fa-regular fa-location-pin-lock', type: 'regular'},
    {name: 'fa-regular fa-plane', type: 'regular'},
    {name: 'fa-regular fa-globe', type: 'regular'},
    {name: 'fa-regular fa-compass', type: 'regular'},
    {name: 'fa-regular fa-map-pin', type: 'regular'},
    {name: 'fa-regular fa-map', type: 'regular'},
    {name: 'fa-regular fa-car', type: 'regular'},
    {name: 'fa-regular fa-bus', type: 'regular'},
    {name: 'fa-regular fa-heart', type: 'regular'},
    {name: 'fa-regular fa-diamond', type: 'regular'},
    {name: 'fa-regular fa-user', type: 'regular'},
    {name: 'fa-regular fa-users', type: 'regular'},
    {name: 'fa-regular fa-user-secret', type: 'regular'},
    {name: 'fa-regular fa-user-minus', type: 'regular'},
    {name: 'fa-regular fa-user-nurse', type: 'regular'},
    {name: 'fa-regular fa-user-plus', type: 'regular'},
    {name: 'fa-regular fa-user-tie', type: 'regular'},
    {name: 'fa-regular fa-users-viewfinder', type: 'regular'},
    {name: 'fa-regular fa-users-slash', type: 'regular'},
    {name: 'fa-regular fa-users-rectangle', type: 'regular'},
    {name: 'fa-regular fa-users-rays', type: 'regular'},
    {name: 'fa-regular fa-users-line', type: 'regular'},
    {name: 'fa-regular fa-users-gear', type: 'regular'},
    {name: 'fa-regular fa-users-between-lines', type: 'regular'},
    {name: 'fa-regular fa-user-xmark', type: 'regular'},
    {name: 'fa-regular fa-user-tag', type: 'regular'},
    {name: 'fa-regular fa-user-slash', type: 'regular'},
    {name: 'fa-regular fa-user-shield', type: 'regular'},
    {name: 'fa-regular fa-user-pen', type: 'regular'},
    {name: 'fa-regular fa-user-ninja', type: 'regular'},
    {name: 'fa-regular fa-user-group', type: 'regular'},
    {name: 'fa-regular fa-user-graduate', type: 'regular'},
    {name: 'fa-regular fa-user-gear', type: 'regular'},
    {name: 'fa-regular fa-user-doctor', type: 'regular'},
    {name: 'fa-regular fa-user-clock', type: 'regular'},
    {name: 'fa-regular fa-user-check', type: 'regular'},
    {name: 'fa-regular fa-user-astronaut', type: 'regular'},
    {name: 'fa-regular fa-circle-user', type: 'regular'},
    {name: 'fa-regular fa-house-user', type: 'regular'},
    {name: 'fa-regular fa-hospital-user', type: 'regular'},
    {name: 'fa-regular fa-clipboard-user', type: 'regular'},
    {name: 'fa-regular fa-chalkboard-user', type: 'regular'},
    {name: 'fa-regular fa-building-user', type: 'regular'},
    {name: 'fa-regular fa-house-chimney-user', type: 'regular'},
    {name: 'fa-regular fa-baby', type: 'regular'},
    {name: 'fa-regular fa-people-arrows', type: 'regular'},
    {name: 'fa-regular fa-wheelchair', type: 'regular'},
    {name: 'fa-regular fa-universal-access', type: 'regular'},
    {name: 'fa-regular fa-people-carry-box', type: 'regular'},
    {name: 'fa-regular fa-poo', type: 'regular'},
    {name: 'fa-regular fa-face-smile', type: 'regular'},
    {name: 'fa-regular fa-person', type: 'regular'},
    {name: 'fa-regular fa-person-dress', type: 'regular'},
    {name: 'fa-regular fa-address-book', type: 'regular'},
    {name: 'fa-regular fa-street-view', type: 'regular'},
    {name: 'fa-regular fa-address-card', type: 'regular'},
    {name: 'fa-regular fa-restroom', type: 'regular'},
    {name: 'fa-regular fa-child', type: 'regular'},
    {name: 'fa-regular fa-skull', type: 'regular'},
    {name: 'fa-regular fa-person-walking-with-cane', type: 'regular'},
    {name: 'fa-regular fa-person-walking-luggage', type: 'regular'},
    {name: 'fa-regular fa-person-walking', type: 'regular'},
    {name: 'fa-regular fa-person-shelter', type: 'regular'},
    {name: 'fa-regular fa-person-running', type: 'regular'},
    {name: 'fa-regular fa-person-pregnant', type: 'regular'},
    {name: 'fa-regular fa-person-praying', type: 'regular'},
    {name: 'fa-regular fa-person-hiking', type: 'regular'},
    {name: 'fa-regular fa-person-drowning', type: 'regular'},
    {name: 'fa-regular fa-people-roof', type: 'regular'},
    {name: 'fa-regular fa-person-biking', type: 'regular'},
    {name: 'fa-regular fa-head-side-virus', type: 'regular'},
    {name: 'fa-regular fa-children', type: 'regular'},
    {name: 'fa-regular fa-child-reaching', type: 'regular'},
    {name: 'fa-regular fa-house-flag', type: 'regular'},
    {name: 'fa-regular fa-industry', type: 'regular'},
    {name: 'fa-regular fa-viruses', type: 'regular'},
    {name: 'fa-regular fa-computer-mouse', type: 'regular'},
    {name: 'fa-regular fa-mug-saucer', type: 'regular'},
    {name: 'fa-regular fa-warehouse', type: 'regular'},
    {name: 'fa-regular fa-server', type: 'regular'},
    {name: 'fa-regular fa-peace', type: 'regular'},
    {name: 'fa-regular fa-staff-snake', type: 'regular'},
    {name: 'fa-regular fa-dragon', type: 'regular'},
    {name: 'fa-regular fa-tower-observation', type: 'regular'},
    {name: 'fa-regular fa-bell-concierge', type: 'regular'},
    {name: 'fa-regular fa-image', type: 'regular'},
    {name: 'fa-regular fa-bars', type: 'regular'},
    {name: 'fa-regular fa-star', type: 'regular'},
    {name: 'fa-regular fa-music', type: 'regular'},
    {name: 'fa-regular fa-cloud', type: 'regular'},
    {name: 'fa-regular fa-pen-nib', type: 'regular'},
    {name: 'fa-regular fa-paperclip', type: 'regular'},
    {name: 'fa-regular fa-file', type: 'regular'},
    {name: 'fa-regular fa-bell', type: 'regular'},
    {name: 'fa-regular fa-cart-shopping', type: 'regular'},
    {name: 'fa-regular fa-clipboard', type: 'regular'},
    {name: 'fa-regular fa-filter', type: 'regular'},
    {name: 'fa-regular fa-alarm-clock', type: 'regular'},
    {name: 'fa-regular fa-bolt', type: 'regular'},
    {name: 'fa-regular fa-ghost', type: 'regular'},
    {name: 'fa-regular fa-rocket-launch', type: 'regular'},
    {name: 'fa-regular fa-pen', type: 'regular'},
    {name: 'fa-regular fa-umbrella', type: 'regular'},
    {name: 'fa-regular fa-gift', type: 'regular'},
    {name: 'fa-regular fa-film', type: 'regular'},
    {name: 'fa-regular fa-list', type: 'regular'},
    {name: 'fa-regular fa-gear', type: 'regular'},
    {name: 'fa-regular fa-trash', type: 'regular'},
    {name: 'fa-regular fa-sparkles', type: 'regular'},
    {name: 'fa-regular fa-lock', type: 'regular'},
    {name: 'fa-regular fa-volume', type: 'regular'},
    {name: 'fa-regular fa-barcode', type: 'regular'},
    {name: 'fa-regular fa-tag', type: 'regular'},
    {name: 'fa-regular fa-book', type: 'regular'},
    {name: 'fa-regular fa-bookmark', type: 'regular'},
    {name: 'fa-regular fa-print', type: 'regular'},
    {name: 'fa-regular fa-fire', type: 'regular'},
    {name: 'fa-regular fa-camera', type: 'regular'},
    {name: 'fa-regular fa-video', type: 'regular'},
    {name: 'fa-regular fa-droplet', type: 'regular'},
    {name: 'fa-regular fa-eye', type: 'regular'},
    {name: 'fa-regular fa-magnet', type: 'regular'},
    {name: 'fa-regular fa-hand', type: 'regular'},
    {name: 'fa-regular fa-folder', type: 'regular'},
    {name: 'fa-regular fa-folder-open', type: 'regular'},
    {name: 'fa-regular fa-thumbs-up', type: 'regular'},
    {name: 'fa-regular fa-thumbs-down', type: 'regular'},
    {name: 'fa-regular fa-comments', type: 'regular'},
    {name: 'fa-regular fa-key', type: 'regular'},
    {name: 'fa-regular fa-thumbtack', type: 'regular'},
    {name: 'fa-regular fa-gears', type: 'regular'},
    {name: 'fa-regular fa-paper-plane', type: 'regular'},
    {name: 'fa-regular fa-truck', type: 'regular'},
    {name: 'fa-regular fa-city', type: 'regular'},
    {name: 'fa-regular fa-tree', type: 'regular'},
    {name: 'fa-regular fa-wifi', type: 'regular'},
    {name: 'fa-regular fa-window', type: 'regular'},
    {name: 'fa-regular fa-burger-soda', type: 'regular'},
    {name: 'fa-regular fa-paint-roller', type: 'regular'},
    {name: 'fa-regular fa-bicycle', type: 'regular'},
    {name: 'fa-regular fa-sliders', type: 'regular'},
    {name: 'fa-regular fa-brush', type: 'regular'},
    {name: 'fa-regular fa-flask', type: 'regular'},
    {name: 'fa-regular fa-briefcase', type: 'regular'},
    {name: 'fa-regular fa-balloons', type: 'regular'},
    {name: 'fa-regular fa-bath', type: 'regular'},
    {name: 'fa-regular fa-handshake', type: 'regular'},
    {name: 'fa-regular fa-snowflake', type: 'regular'},
    {name: 'fa-regular fa-palette', type: 'regular'},
    {name: 'fa-regular fa-layer-group', type: 'regular'},
    {name: 'fa-regular fa-brackets-curly', type: 'regular'},
    {name: 'fa-regular fa-gamepad', type: 'regular'},
    {name: 'fa-regular fa-feather', type: 'regular'},
    {name: 'fa-regular fa-sun', type: 'regular'},
    {name: 'fa-regular fa-computer-classic', type: 'regular'},
    {name: 'fa-regular fa-link', type: 'regular'},
    {name: 'fa-regular fa-play-pause', type: 'regular'},
    {name: 'fa-regular fa-bug', type: 'regular'},
    {name: 'fa-regular fa-shop', type: 'regular'},
    {name: 'fa-regular fa-joystick', type: 'regular'},
    {name: 'fa-regular fa-planet-ringed', type: 'regular'},
    {name: 'fa-regular fa-landmark', type: 'regular'},
    {name: 'fa-regular fa-chart-simple', type: 'regular'},
    {name: 'fa-regular fa-shirt', type: 'regular'},
    {name: 'fa-regular fa-files', type: 'regular'},
    {name: 'fa-regular fa-dolphin', type: 'regular'},
    {name: 'fa-regular fa-anchor', type: 'regular'},
    {name: 'fa-regular fa-quote-left', type: 'regular'},
    {name: 'fa-regular fa-atom-simple', type: 'regular'},
    {name: 'fa-regular fa-bag-shopping', type: 'regular'},
    {name: 'fa-regular fa-bed-front', type: 'regular'},
    {name: 'fa-regular fa-signal-bars', type: 'regular'},
    {name: 'fa-regular fa-code-compare', type: 'regular'},
    {name: 'fa-regular fa-stethoscope', type: 'regular'},
    {name: 'fa-regular fa-car-side', type: 'regular'},
    {name: 'fa-regular fa-ufo', type: 'regular'},
    {name: 'fa-regular fa-aperture', type: 'regular'},
    {name: 'fa-regular fa-bird', type: 'regular'},
    {name: 'fa-regular fa-strawberry', type: 'regular'},
    {name: 'fa-regular fa-crab', type: 'regular'},
    {name: 'fa-regular fa-cable-car', type: 'regular'},
    {name: 'fa-regular fa-moped', type: 'regular'},
    {name: 'fa-regular fa-info', type: 'regular'},
    {name: 'fa-regular fa-play', type: 'regular'},
    {name: 'fa-regular fa-passport', type: 'regular'},
    {name: 'fa-regular fa-question', type: 'regular'},
    {name: 'fa-regular fa-pencil', type: 'regular'},
    {name: 'fa-regular fa-head-side', type: 'regular'},
    {name: 'fa-regular fa-upload', type: 'regular'},
    {name: 'fa-regular fa-computer-speaker', type: 'regular'},
    {name: 'fa-regular fa-database', type: 'regular'},
    {name: 'fa-regular fa-newspaper', type: 'regular'},
    {name: 'fa-regular fa-building', type: 'regular'},
    {name: 'fa-regular fa-globe-stand', type: 'regular'},
    {name: 'fa-regular fa-store', type: 'regular'},
    {name: 'fa-regular fa-file-excel', type: 'regular'},
    {name: 'fa-regular fa-browser', type: 'regular'},
    {name: 'fa-regular fa-shield', type: 'regular'},
    {name: 'fa-regular fa-expand', type: 'regular'},
    {name: 'fa-regular fa-water', type: 'regular'},
    {name: 'fa-regular fa-coin', type: 'regular'},
    {name: 'fa-regular fa-rocket', type: 'regular'},
    {name: 'fa-regular fa-spinner', type: 'regular'},
    {name: 'fa-regular fa-signature', type: 'regular'},
    {name: 'fa-regular fa-icons', type: 'regular'},
    {name: 'fa-regular fa-desktop', type: 'regular'},
    {name: 'fa-regular fa-watch', type: 'regular'},
    {name: 'fa-regular fa-vials', type: 'regular'},
    {name: 'fa-regular fa-language', type: 'regular'},
    {name: 'fa-regular fa-brain', type: 'regular'},
    {name: 'fa-regular fa-hotel', type: 'regular'},
    {name: 'fa-regular fa-marker', type: 'regular'},
    {name: 'fa-regular fa-shower', type: 'regular'},
    {name: 'fa-regular fa-glass', type: 'regular'},
    {name: 'fa-regular fa-mailbox', type: 'regular'},
    {name: 'fa-regular fa-badge', type: 'regular'},
    {name: 'fa-regular fa-wallet', type: 'regular'},
    {name: 'fa-regular fa-award', type: 'regular'},
    {name: 'fa-regular fa-toggle-on', type: 'regular'},
    {name: 'fa-regular fa-ship', type: 'regular'},
    {name: 'fa-regular fa-hands', type: 'regular'},
    {name: 'fa-regular fa-radar', type: 'regular'},
    {name: 'fa-regular fa-motorcycle', type: 'regular'},
    {name: 'fa-regular fa-text-size', type: 'regular'},
    {name: 'fa-regular fa-train', type: 'regular'},
    {name: 'fa-solid fa-books', type: 'regular'},
    {name: 'fa-regular fa-wrench', type: 'regular'},
    {name: 'fa-regular fa-microchip', type: 'regular'},
    {name: 'fa-regular fa-trophy', type: 'regular'},
    {name: 'fa-regular fa-hammer', type: 'regular'},
    {name: 'fa-regular fa-file-pdf', type: 'regular'},
    {name: 'fa-regular fa-solar-system', type: 'regular'},
    {name: 'fa-regular fa-scanner-touchscreen', type: 'regular'},
    {name: 'fa-regular fa-meat', type: 'regular'},
    {name: 'fa-regular fa-radio', type: 'regular'},
    {name: 'fa-regular fa-album', type: 'regular'},
    {name: 'fa-regular fa-chair', type: 'regular'},
    {name: 'fa-regular fa-route', type: 'regular'},
    {name: 'fa-regular fa-plug', type: 'regular'},
    {name: 'fa-regular fa-calculator', type: 'regular'},
    {name: 'fa-regular fa-certificate', type: 'regular'},
    {name: 'fa-regular fa-fingerprint', type: 'regular'},
    {name: 'fa-regular fa-road', type: 'regular'},
    {name: 'fa-regular fa-crosshairs', type: 'regular'},
    {name: 'fa-regular fa-heading', type: 'regular'},
    {name: 'fa-regular fa-church', type: 'regular'},
    {name: 'fa-regular fa-joint', type: 'regular'},
    {name: 'fa-regular fa-recycle', type: 'regular'},
    {name: 'fa-regular fa-lightbulb', type: 'regular'},
    {name: 'fa-regular fa-staff', type: 'regular'},
    {name: 'fa-regular fa-stamp', type: 'regular'},
    {name: 'fa-regular fa-kidneys', type: 'regular'},
    {name: 'fa-regular fa-microwave', type: 'regular'},
    {name: 'fa-regular fa-wreath', type: 'regular'},
    {name: 'fa-regular fa-window-frame', type: 'regular'},
    {name: 'fa-regular fa-wifi-slash', type: 'regular'},
    {name: 'fa-regular fa-waveform', type: 'regular'},
    {name: 'fa-regular fa-wand', type: 'regular'},
    {name: 'fa-regular fa-tv', type: 'regular'},
    {name: 'fa-regular fa-trumpet', type: 'regular'},
    {name: 'fa-regular fa-truck-moving', type: 'regular'},
    {name: 'fa-regular fa-truck-flatbed', type: 'regular'},
    {name: 'fa-regular fa-trash-can', type: 'regular'},
    {name: 'fa-regular fa-tooth', type: 'regular'},
    {name: 'fa-regular fa-timeline', type: 'regular'},
    {name: 'fa-regular fa-tent', type: 'regular'},
    {name: 'fa-regular fa-teeth', type: 'regular'},
    {name: 'fa-regular fa-tarp', type: 'regular'},
    {name: 'fa-regular fa-suitcase', type: 'regular'},
    {name: 'fa-regular fa-stopwatch', type: 'regular'},
    {name: 'fa-regular fa-stapler', type: 'regular'},
    {name: 'fa-regular fa-stairs', type: 'regular'},
    {name: 'fa-regular fa-spoon', type: 'regular'},
    {name: 'fa-regular fa-split', type: 'regular'},
    {name: 'fa-regular fa-spa', type: 'regular'},
    {name: 'fa-regular fa-socks', type: 'regular'},
    {name: 'fa-regular fa-snowman', type: 'regular'},
    {name: 'fa-regular fa-snooze', type: 'regular'},
    {name: 'fa-regular fa-snake', type: 'regular'},
    {name: 'fa-regular fa-smoking', type: 'regular'},
    {name: 'fa-regular fa-skull-crossbones', type: 'regular'},
    {name: 'fa-regular fa-siren-on', type: 'regular'},
    {name: 'fa-regular fa-sidebar', type: 'regular'},
    {name: 'fa-regular fa-shovel', type: 'regular'},
    {name: 'fa-regular fa-shoe-prints', type: 'regular'},
    {name: 'fa-regular fa-shield-quartered', type: 'regular'},
    {name: 'fa-regular fa-share-nodes', type: 'regular'},
    {name: 'fa-regular fa-sheet-plastic', type: 'regular'},
    {name: 'fa-regular fa-share-all', type: 'regular'},
    {name: 'fa-regular fa-shapes', type: 'regular'},
    {name: 'fa-regular fa-sensor', type: 'regular'},
    {name: 'fa-regular fa-scarf', type: 'regular'},
    {name: 'fa-regular fa-screen-users', type: 'regular'},
    {name: 'fa-regular fa-scissors', type: 'regular'},
    {name: 'fa-regular fa-scalpel', type: 'regular'},
    {name: 'fa-regular fa-scanner-image', type: 'regular'},
    {name: 'fa-regular fa-saxophone', type: 'regular'},
    {name: 'fa-regular fa-sailboat', type: 'regular'},
    {name: 'fa-regular fa-sack', type: 'regular'},
    {name: 'fa-regular fa-rug', type: 'regular'},
    {name: 'fa-regular fa-rss', type: 'regular'},
    {name: 'fa-regular fa-router', type: 'regular'},
    {name: 'fa-regular fa-road-barrier', type: 'regular'},
    {name: 'fa-regular fa-ribbon', type: 'regular'},
    {name: 'fa-regular fa-reel', type: 'regular'},
    {name: 'fa-regular fa-ram', type: 'regular'},
    {name: 'fa-regular fa-rainbow', type: 'regular'},
    {name: 'fa-regular fa-rabbit', type: 'regular'},
    {name: 'fa-regular fa-quotes', type: 'regular'},
    {name: 'fa-regular fa-q', type: 'regular'},
    {name: 'fa-regular fa-puzzle', type: 'regular'},
    {name: 'fa-regular fa-pump', type: 'regular'},
    {name: 'fa-regular fa-popcorn', type: 'regular'},
    {name: 'fa-regular fa-prescription', type: 'regular'},
    {name: 'fa-regular fa-podcast', type: 'regular'},
    {name: 'fa-regular fa-pizza-slice', type: 'regular'},
    {name: 'fa-regular fa-pipe', type: 'regular'},
    {name: 'fa-regular fa-person-swimming', type: 'regular'},
    {name: 'fa-regular fa-paw', type: 'regular'},
    {name: 'fa-regular fa-paragraph', type: 'regular'},
    {name: 'fa-regular fa-paper-plane-top', type: 'regular'},
    {name: 'fa-regular fa-panorama', type: 'regular'},
    {name: 'fa-regular fa-pancakes', type: 'regular'},
    {name: 'fa-regular fa-pallet', type: 'regular'},
    {name: 'fa-regular fa-pager', type: 'regular'},
    {name: 'fa-regular fa-page', type: 'regular'},
    {name: 'fa-regular fa-oven', type: 'regular'},
    {name: 'fa-regular fa-ornament', type: 'regular'},
    {name: 'fa-regular fa-onion', type: 'regular'},
    {name: 'fa-regular fa-oil-can', type: 'regular'},
    {name: 'fa-regular fa-oil-can-drip', type: 'regular'},
    {name: 'fa-regular fa-olive', type: 'regular'},
    {name: 'fa-regular fa-nose', type: 'regular'},
    {name: 'fa-regular fa-music-note', type: 'regular'},
    {name: 'fa-regular fa-mountain', type: 'regular'},
    {name: 'fa-regular fa-merge', type: 'regular'},
    {name: 'fa-regular fa-mercury', type: 'regular'},
    {name: 'fa-regular fa-memory', type: 'regular'},
    {name: 'fa-regular fa-mask-face', type: 'regular'},
    {name: 'fa-regular fa-mango', type: 'regular'},
    {name: 'fa-regular fa-mandolin', type: 'regular'},
    {name: 'fa-regular fa-lips', type: 'regular'},
    {name: 'fa-regular fa-memo', type: 'regular'},
    {name: 'fa-regular fa-knife', type: 'regular'},
    {name: 'fa-regular fa-kiwi-fruit', type: 'regular'},
    {name: 'fa-regular fa-jug', type: 'regular'},
    {name: 'fa-regular fa-jug-bottle', type: 'regular'},
    {name: 'fa-regular fa-jar', type: 'regular'},
    {name: 'fa-regular fa-inboxes', type: 'regular'},
    {name: 'fa-regular fa-inbox-out', type: 'regular'},
    {name: 'fa-regular fa-inbox-in', type: 'regular'},
    {name: 'fa-regular fa-inbox-full', type: 'regular'},
    {name: 'fa-regular fa-helicopter-symbol', type: 'regular'},
    {name: 'fa-regular fa-helicopter', type: 'regular'},
    {name: 'fa-regular fa-gun', type: 'regular'},
    {name: 'fa-regular fa-graduation-cap', type: 'regular'},
    {name: 'fa-regular fa-gif', type: 'regular'},
    {name: 'fa-regular fa-football-helmet', type: 'regular'},
    {name: 'fa-regular fa-flashlight', type: 'regular'},
    {name: 'fa-regular fa-filters', type: 'regular'},
    {name: 'fa-regular fa-fill', type: 'regular'},
    {name: 'fa-regular fa-file-prescription', type: 'regular'},
    {name: 'fa-regular fa-file-powerpoint', type: 'regular'},
    {name: 'fa-regular fa-file-pen', type: 'regular'},
    {name: 'fa-regular fa-file-music', type: 'regular'},
    {name: 'fa-regular fa-ferris-wheel', type: 'regular'},
    {name: 'fa-regular fa-escalator', type: 'regular'},
    {name: 'fa-regular fa-engine', type: 'regular'},
    {name: 'fa-regular fa-egg', type: 'regular'},
    {name: 'fa-regular fa-cowbell', type: 'regular'},
    {name: 'fa-regular fa-comment-sms', type: 'regular'},
    {name: 'fa-regular fa-clapperboard', type: 'regular'},
    {name: 'fa-regular fa-check-double', type: 'regular'},
    {name: 'fa-regular fa-castle', type: 'regular'},
    {name: 'fa-regular fa-cards-blank', type: 'regular'},
    {name: 'fa-regular fa-cactus', type: 'regular'},
    {name: 'fa-regular fa-butter', type: 'regular'},
    {name: 'fa-regular fa-burger', type: 'regular'},
    {name: 'fa-regular fa-bone', type: 'regular'},
    {name: 'fa-regular fa-bolt-lightning', type: 'regular'},
    {name: 'fa-regular fa-bluetooth', type: 'regular'},
    {name: 'fa-regular fa-block-brick', type: 'regular'},
    {name: 'fa-regular fa-apartment', type: 'regular'},
    {name: 'fa-regular fa-apostrophe', type: 'regular'},
    {name: 'fa-brands fa-facebook', type: 'brand'},
    {name: 'fa-brands fa-facebook-messenger', type: 'brand'},
    {name: 'fa-brands fa-facebook-f', type: 'brand'},
    {name: 'fa-brands fa-square-facebook', type: 'brand'},
    {name: 'fa-brands fa-instagram', type: 'brand'},
    {name: 'fa-brands fa-square-instagram', type: 'brand'},
    {name: 'fa-brands fa-twitter', type: 'brand'},
    {name: 'fa-brands fa-square-twitter', type: 'brand'},
    {name: 'fa-brands fa-skype', type: 'brand'},
    {name: 'fa-brands fa-linkedin', type: 'brand'},
    {name: 'fa-brands fa-linkedin-in', type: 'brand'},
    {name: 'fa-brands fa-cc-visa', type: 'brand'},
    {name: 'fa-brands fa-cc-mastercard', type: 'brand'},
    {name: 'fa-brands fa-cc-stripe', type: 'brand'},
    {name: 'fa-brands fa-cc-paypal', type: 'brand'},
    {name: 'fa-brands fa-cc-jcb', type: 'brand'},
    {name: 'fa-brands fa-cc-amazon-pay', type: 'brand'},
    {name: 'fa-brands fa-accessible-icon', type: 'brand'},
    {name: 'fa-brands fa-uber', type: 'brand'},
    {name: 'fa-brands fa-aws', type: 'brand'},
    {name: 'fa-brands fa-servicestack', type: 'brand'},
    {name: 'fa-brands fa-tiktok', type: 'brand'},
    {name: 'fa-brands fa-discord', type: 'brand'},
    {name: 'fa-brands fa-youtube', type: 'brand'},
    {name: 'fa-brands fa-github', type: 'brand'},
    {name: 'fa-brands fa-wordpress', type: 'brand'},
    {name: 'fa-brands fa-docker', type: 'brand'},
    {name: 'fa-brands fa-apple', type: 'brand'},
    {name: 'fa-brands fa-google', type: 'brand'},
    {name: 'fa-brands fa-windows', type: 'brand'},
    {name: 'fa-brands fa-paypal', type: 'brand'},
    {name: 'fa-brands fa-dropbox', type: 'brand'},
    {name: 'fa-brands fa-squarespace', type: 'brand'},
    {name: 'fa-brands fa-android', type: 'brand'},
    {name: 'fa-brands fa-shopify', type: 'brand'},
    {name: 'fa-brands fa-medium', type: 'brand'},
    {name: 'fa-brands fa-codepen', type: 'brand'},
    {name: 'fa-brands fa-cloudflare', type: 'brand'},
    {name: 'fa-brands fa-whatsapp', type: 'brand'},
    {name: 'fa-brands fa-intercom', type: 'brand'},
    {name: 'fa-brands fa-internet-explorer', type: 'brand'},
    {name: 'fa-brands fa-telegram', type: 'brand'},
    {name: 'fa-brands fa-readme', type: 'brand'},
    {name: 'fa-brands fa-wikipedia-w', type: 'brand'},
    {name: 'fa-brands fa-java', type: 'brand'},
    {name: 'fa-brands fa-linux', type: 'brand'},
    {name: 'fa-brands fa-rebel', type: 'brand'},
    {name: 'fa-brands fa-elementor', type: 'brand'},
    {name: 'fa-brands fa-untappd', type: 'brand'},
    {name: 'fa-brands fa-uikit', type: 'brand'},
    {name: 'fa-brands fa-unity', type: 'brand'},
    {name: 'fa-brands fa-sketch', type: 'brand'},
    {name: 'fa-brands fa-sitrox', type: 'brand'},
    {name: 'fa-brands fa-sellcast', type: 'brand'},
    {name: 'fa-brands fa-rev', type: 'brand'},
    {name: 'fa-brands fa-renren', type: 'brand'},
    {name: 'fa-brands fa-pix', type: 'brand'},
    {name: 'fa-brands fa-pushed', type: 'brand'},
    {name: 'fa-brands fa-osi', type: 'brand'},
    {name: 'fa-brands fa-orcid', type: 'brand'},
    {name: 'fa-brands fa-odysee', type: 'brand'},
    {name: 'fa-brands fa-opera', type: 'brand'},
    {name: 'fa-brands fa-opencart', type: 'brand'},
    {name: 'fa-brands fa-mix', type: 'brand'},
    {name: 'fa-brands fa-meta', type: 'brand'},
    {name: 'fa-brands fa-magento', type: 'brand'},
    {name: 'fa-brands fa-korvue', type: 'brand'},
    {name: 'fa-brands fa-jenkins', type: 'brand'},
    {name: 'fa-brands fa-jira', type: 'brand'},
    {name: 'fa-brands fa-jsfiddle', type: 'brand'},
    {name: 'fa-brands fa-itunes-note', type: 'brand'},
    {name: 'fa-brands fa-keycdn', type: 'brand'},
    {name: 'fa-brands fa-mizuni', type: 'brand'},
    {name: 'fa-brands fa-megaport', type: 'brand'},
    {name: 'fa-brands fa-mendeley', type: 'brand'},
    {name: 'fa-brands fa-lyft', type: 'brand'},
    {name: 'fa-brands fa-lastfm', type: 'brand'},
    {name: 'fa-brands fa-less', type: 'brand'},
    {name: 'fa-brands fa-keybase', type: 'brand'},
    {name: 'fa-brands fa-kaggle', type: 'brand'},
    {name: 'fa-brands fa-js', type: 'brand'},
    {name: 'fa-brands fa-joomla', type: 'brand'},
    {name: 'fa-brands fa-itch-io', type: 'brand'},
    {name: 'fa-brands fa-jedi-order', type: 'brand'},
      ]
  default: any = {
    headings: [],
    texts: [],
    buttons: [],
    dividers: [],
    videos: [],
    checkouts: [],
    codes: [],
  }
  constructor(private _general: GeneralService, private _row: RowService, private _style: StyleService, private _section: SectionService) {
  }
  getDialogueEvent(): Observable<any> {
    return this.distroyDialogue.asObservable();
  }

  setMenu(element: any, menu: any) {
    element.data_id = menu.id;
    element.items = JSON.parse(JSON.stringify(menu.items));
    return element;
  }

  setIframe(element: any, adata: any) {
    element.data_id = adata.uniqueid;
    element.src = window.origin + '/fetch-form/' + adata.user_id + '/' + adata.uniqueid;
    return element;
  }

  addElement(element: any) {
    if (element.btntype == 'upsell' || element.btntype == 'downsell') {
      var proId = this._general.step_products[0];
      element.productid = proId ? proId.uniqueid : '';
    }
    else if (element.name == 'menu') {
      if (element?.itemset) delete element?.itemset;
      else element = this.setMenu(element, JSON.parse(JSON.stringify(this._general.menus[0])));
    }
    else if (element.name == 'iframe' && element.type == 'form') {
      if (element?.itemset) delete element?.itemset;
      else element = this.setIframe(element, JSON.parse(JSON.stringify(this._general.forms[0])));
    }
    var tempObj = JSON.parse(JSON.stringify(this.elementObj));
    tempObj.content = JSON.parse(JSON.stringify(element));
    if (element.name != 'iframe' && element.name != 'code') {
      var fntSz = '14px';
      switch(tempObj.content.name) {
        case 'heading': 
          fntSz = '24px';
        break; 
        case 'icon': 
          fntSz = '16px';
        break;   
        default:
          fntSz = '14px';
      }
      var respS: any = { 'font-size': fntSz };
      if(element.name == 'menu') {
        tempObj.content.style = {
          desktop: this._style.defaultStyling(tempObj),
          tablet_h: '',
          tablet_v: '',
          mobile: ''
        }
        tempObj.dropdownstyle = true;
        tempObj.content.style.dropdown = this._style.defaultStyling(tempObj);
        delete tempObj.dropdownstyle;
      }
      else if (element.name == 'form' || element.name == 'divider') {
        respS = { 'width': '100%'};
        tempObj.content.style = {
          desktop: this._style.defaultStyling(tempObj),
          tablet_h: '',
          tablet_v: respS,
          mobile: respS
        }
      }
      else {
        tempObj.content.style = {
          desktop: this._style.defaultElementStyling(tempObj),
          tablet_h: '',
          tablet_v: respS,
          mobile: respS
        }
      }
      if (element.items) {
        tempObj.itemstyle = true;
        var eleS = this._style.defaultElementStyling(tempObj);
        tempObj.content.item = {
          style: {
            desktop: eleS,
            tablet_h: '',
            tablet_v: respS,
            mobile: respS,
          }
        }
        if(element.name == 'menu') tempObj.content.item.style.dropdown = eleS;
        delete tempObj.itemstyle;
        console.log(tempObj);
      }
      if (element.form) return tempObj;
    }
    this.appendElement(tempObj, this.element_index);
    this.distroyDialogue.next(void 0);
  }

  duplicateElement(element: any, index: any) {
    var tempObj = JSON.parse(JSON.stringify(element));
    this.appendElement(tempObj, index);
  }

  deleteElement(elements: any[], index: any) {
    elements.splice(index, 1);
    this._section.savePageSession();
  }

  appendElement(tempObj: any, index: number) {
    tempObj.id = this._general.createBlockId(tempObj);
    tempObj.setting = false;
    this.selectedElements.splice(index + 1, 0, tempObj);
    this._section.savePageSession();
  }
}

